### ISSUE TITLE
Very bad wifi signal

### ISSUE THREAD

**Issue by Jason2866** [Xinyuan-LilyGO/LilyGo-T-OI-PLUS#10]
Compiled a Arduino ESP32 framework with the glitch fix (#3).
https://github.com/Jason2866/esp32-arduino-lib-builder/releases/download/427/framework-arduinoespressif32-master-583026f04.tar.gz So https://github.com/espressif/esp-idf/issues/7082 is solved. No more boot loops. But signal is -76dBM at 1 meter of Wifi AP, far too low.
Source code: https://github.com/arendst/Tasmota
Compiled binary https://jason2866.github.io/Tasmota-specials/
Other C3 (revision 3 too) boards do work without any issue!
See screenshot from running Tasmota on a AI-Thinker ESP-C3-01M module
![Screenshot_20210911-205200](https://user-images.githubusercontent.com/24528715/132958460-e9e28cc5-c680-44dd-abc2-50f976a4dc1d.png)

**Comment by LilyGO** [comment]
Sorry for the inconvenience, the new version has been updated to fix it.
