### ISSUE TITLE
Micropython for this board

### ISSUE THREAD

**Issue by wolfen351** [Xinyuan-LilyGO/LilyGo-T-OI-PLUS#13]
Hi there
I'm new at this, but I understand I need to flash micropython onto the board before I can write python code for it. Where can I find that image?

Thanks!

**Comment by ryanaross** [comment]
I was able to flash micropython to this board no problems using the one available here.
https://micropython.org/download/esp32c3/
Just make sure to change `-z 0x1000` to `-z 0x0` 
Micropython works great so far on this board!

**Comment by wolfen351** [comment]
Thanks! Worked perfectly! :)
