### ISSUE TITLE
USB & Battery high power consumption during deep sleep

### ISSUE THREAD

**Issue by mailinger-mate** [Xinyuan-LilyGO/LilyGo-T-OI-PLUS#21]
Hello,

Based on #8 I confirmed the power consumption on *battery only* to be *40 uA* during deep sleep.

However with a fully charged *battery and USB* both connected the power consumption never goes below *35 mA*.
I am using the [deep sleep example](https://github.com/Xinyuan-LilyGO/LilyGo-T-OI-PLUS/blob/main/example/deepsleep/deepsleep.ino) provided in the repository.

How can i have external power with backup battery and charging while preserving low power consumption in deep sleep?

Thank you,
Mate

**Comment by LilyGO** [comment]
Hello, Test power can only use battery test !

**Comment by mailinger-mate** [comment]
@LilyGO what alternatives do I have?

**Comment by ekawahyu** [comment]
@mailinger-mate I am sorry for seeing your message late. I am afraid you are gonna need a new design on the power management part. I hope that helps!

**Comment by mailinger-mate** [comment]
@ekawahyu will Lilygo release a board with an improved or alternative design that fixes this?

**Comment by ekawahyu** [comment]
I think that question is for LilyGo to answer. In my case, I made my own design to fit my requirement, with better low quiescent LDO and for some I completely remove it.
