### ISSUE TITLE
Which pins support PWM?

### ISSUE THREAD

**Issue by esranonff** [Xinyuan-LilyGO/LilyGo-T-OI-PLUS#22]
This board looks idea for a project I'm working on, however I can't see which pins support PWM on the pin-out diagram.

I've tried various options on the board along with `analogWrite(<pin>, <valule>);` but can't even get a basic LED to fade.

Where am I going wrong?

**Comment by LilyGO** [comment]
ESP32 does not support the analogWrite() function. Use the ledcWrite() function. Refer to the official example .

**Comment by esranonff** [comment]
@LilyGO perfect, thanks, this is my first foray into "proper" ESP32 territory, I've been using ESP8266's up until now!
