### ISSUE TITLE
LILYGO TTGO T-OI Plus ESP32-C3 with 18650 battery

### ISSUE THREAD

**Issue by jnule1a** [Xinyuan-LilyGO/LilyGo-T-OI-PLUS#26]
Can LILYGO TTGO T-OI Plus ESP32-C3 charge a 3000mAh 18650 battery and how long does it take to fully charge it ?

**Comment by mailinger-mate** [comment]
Yes, when the board is connected with USB-C, it will also charge the 18650 battery. I haven't measured the charging characteristics but if I remember correctly, it took maybe 10-20 minutes to charge from 80%..
