### ISSUE TITLE
Board "ESP32C3 Dev Module" not found in the list of boards for ESP32

### ISSUE THREAD

**Issue by edmund-troche** [Xinyuan-LilyGO/LilyGo-T-OI-PLUS#9]
I've used the boards index in the README.md, but there is no board with the name "ESP32C3 Dev Module". Did the board name change from the T-IO-Plus? Should I use a different board list?

Thanks

**Comment by al1fch** [comment]
@edmund-troche 

ESP32-C3 is (partially) supported by 2.0.0-RC2 version if the core fir Arduino IDE, so ESP32C3 Dev Module is seen in  board's list for this version

**Comment by edmund-troche** [comment]
@al1fch Thanks for the info, I'll check it out
